carts/urls.py
from django.urls import path
from .views import cart_home , cart_update

urlpatterns = [
    path('', cart_home, name='cart-home' ),
    path('update' , cart_update , name='cart-update' ),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page,contactView,loginView
from django.contrib.auth import views as auth_view
from users import views as user_views


urlpatterns = [

    path('', home_page, name='home'),
    path('register/', user_views.register,name='register'),
    path('profile/', user_views.profile,name='profile'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html') , name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html') , name='logout'),
    path('password-reset/',
         auth_view.PasswordResetView.as_view(
             template_name='password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_view.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'
         ),
        name='password_reset_confirm'),

    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    path('activate/<uidb64>/<token>/',user_views.activate, name='activate'),

    path('products/', include('products.urls')),
    path('contact/',contactView,name='contact'),
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from .views import SearchListView

app_name='search'


urlpatterns = [
    path('',SearchListView.as_view(),name='query' ),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from products.models import Product

# Create your views here.

class SearchListView(ListView):
    model = Product
    template_name = 'search/list.html'

    def get_queryset(self):
        request = self.request
        print(request.GET.get('q'))
        # query = self.request.GET.
        if self.request.GET.get('q'):
            q_set = Product.objects.search(self.request.GET.get('q'))

            if len(q_set)>0:
                return q_set
            else:
                return Product.objects.featured()

        return Product.objects.featured()

search/templates/search/list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        {% if request.GET.q %}
            <div class="col-12 mb-3">
                Result For <b>{{request.GET.q}}</b>
            </div>

            <div class="col-12 col-md-8 mx-auto py-4">
                {% include 'search/search_form.html' %}
            </div>
        {% endif %}
    </div>


    {% for product in object_list %}
        <p><a href="{{ product.get_absolute_url }}">Product Name: {{product.name}}</a></p>
    {% endfor %}
{% endblock %}

search/templates/search/search_form.html
<form class="form my-2 my-lg-0" method="GET" action="{% url 'search:query' %}">

    <div class="input-group">
        <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value="{{request.GET.q}}">
        <span class="input-group-btn">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </span>
        
      </div>
</form>